# 数据库相关配置
spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3300/queue?useUnicode=true&useSSL=false
      username: root
      password: 123456
      # hikari 的相关配置
      continue-on-error: true
      maximum-pool-size: 20
      minimum-idle: 5
      auto-commit: true
      connection-test-query: SELECT 1

# mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto   # 可以拿到返回的主键id

# 本地调试开启跨域
isOpenCors: true
